name: Publish CUDA11.2 Develop
on:
  workflow_dispatch:
  push:
    tags:
      - v*
env:
  CUDA_VER: "11-2"
  CUDA_VERSION: "11.2"
  TF_VERSION: "2.6.0"
  CUDA_CUDART_VERSION: "11.2.152-1"
  DOCKERHUB_REPO: "modelbox/modelbox-devel-tensorflow_2.6.0-cuda_11.2-ubuntu-x86_64"
  IMAGE_VERSION: "1.0.0"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkfile
        run: ls -lh ./*

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/Dockerfile.cuda112.x86_64.build
          build-args: |
            CUDA_VER=${{ env.CUDA_VER }}
            CUDA_VERSION=${{ env.CUDA_VERSION }}
            TF_VERSION=${{ env.TF_VERSION }}
            CUDA_CUDART_VERSION=${{ env.CUDA_CUDART_VERSION }}
            IMAGE_VERSION=${{ env.IMAGE_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_VERSION }}
