name: Publish CUDA10.2_torch Develop
on:
  workflow_dispatch:
  push:
    tags:
      - v*
env:
  BUILD_TYPE: Release
  CUDA_VER: "10-2"
  CUDA_VERSION: "10.2"
  CUDA_CUDART_VERSION: "10.2.89-1"
  TORCH_VERSION: "1.9.1"
  VIDEOSDK_VERSION: "9.1.23"
  DOCKERHUB_REPO: "modelbox/modelbox-develop-libtorch_1.9.1-cuda_10.2-ubuntu-x86_64"
  IMAGE_VERSION: "v1.1.3"

jobs:
  compile:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo "Asia/Shanghai" > /etc/timezone
        apt-get update
        apt-get upgrade -y
        apt-get remove --purge python3-apt
        apt-get install --no-install-recommends -y dbus iproute2 gnupg2 curl ca-certificates
        apt-get install -y python3.7-dev python3-pip python3-apt python3-setuptools
        rm -f /usr/bin/python3 /usr/bin/python
        ln -s python3.7 /usr/bin/python3
        ln -s python3 /usr/bin/python
        apt-get install -y \
            build-essential unzip ffmpeg sudo bash vim gdb git doxygen autoconf cmake openssh-server \
            python3-wheel python3-numpy python3-opencv libopencv-dev pkg-config kmod net-tools pciutils \
            libssl-dev libcpprest-dev libswscale-dev libavformat-dev graphviz libgraphviz-dev libfuse-dev \
            libprotobuf-c-dev protobuf-c-compiler duktape-dev libmosquitto-dev
    - name: Install cuda+torch
      run: |
        curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | apt-key add -
        cp -af ./docker/repo/*.list /etc/apt/sources.list.d/
        apt-get update
        apt-get install -y --no-install-recommends \
           cuda-cudart-${CUDA_VER}=${CUDA_CUDART_VERSION} \
           cuda-compat-${CUDA_VER} \
           cuda-minimal-build-${CUDA_VER} \
           cuda-libraries-dev-${CUDA_VER} \
           cuda-command-line-tools-${CUDA_VER}
        ln -s cuda-${CUDA_VERSION} /usr/local/cuda
        find /usr/ -name *cudnn*|xargs sudo rm -fr
        apt-get install -y libcudnn7-dev=7.6.5.32-1+cuda10.2 
        curl -LJO https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.9.1%2Bcu102.zip
        unzip libtorch-*.zip -d . >/dev/null 2>&1
        cp -af libtorch/* /usr/local/
        rm -rf /var/lib/apt/lists/*
    - name: Install ThirdParty
      run: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        apt-get install -y nodejs
        npm install -g npm@latest
        npm install -g @angular/cli
        npm cache clean --force

        curl -LJO https://github.com/zxk114/modelbox/releases/download/binary/obs-dev.tar.gz
        tar zxf obs-dev.tar.gz -C /usr/local/
        curl -LJO https://github.com/zxk114/modelbox/releases/download/binary/Video_Codec_SDK_${VIDEOSDK_VERSION}.tar.gz
        tar zxf Video_Codec_SDK_${VIDEOSDK_VERSION}.tar.gz -C /usr/local/
        ln -s libnvcuvid.so /usr/local/lib/libnvcuvid.so.1
        ln -s /usr/local/cuda/lib64/libcublas.so.10 /usr/local/lib/libcublas.so.10.2
        cp -af /usr/local/cuda/compat/* /usr/local/lib/

        curl -LJO https://download.java.net/java/GA/jdk17.0.1/2a2082e5a09d4267845be086888add4f/12/GPL/openjdk-17.0.1_linux-x64_bin.tar.gz
        tar zxf openjdk-17.0.1_linux-x64_bin.tar.gz -C /usr/local/
        curl -LJO https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
        tar zxf apache-maven-3.8.4-bin.tar.gz -C /usr/local/
        ls -lh /usr/local/*

        yes | python3 -m pip install --upgrade pip
        yes | pip3 install pillow numpy
    - name: Configure env
      run: |
        export JAVA_HOME=/usr/lib/jvm/jdk-17
        export MAVEN_HOME=/usr/local/apache-maven-3.8.3
        export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/lib:/usr/local/cuda/lib64/stubs${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
        export PATH=/usr/local/cuda/bin:$JAVA_HOME/bin:$MAVEN_HOME/bin${PATH:+:${PATH}}
        export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
    - name: CMake
      run: |
        pwd
        ls -lh .
        ldconfig
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_WEB_UI=on
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        make package -j4
        rm -f release/*.rpm
        ls -lh release
        filecount=$(ls release | wc -l)
        dpkgcount=$(ls release | egrep "*.deb" | wc -l)
        artifacts_file=$(ls ${artifacts_path} | grep "cuda"| wc -l)
        if [ ${filecount} -ge 13 ] && [ ${dpkgcount} -ge 11 ] && [ ${artifacts_file} -eq 2 ]; then
            echo "compile success"
        else
            echo "compile failed"
            exit 1
        fi
    - name: upload-artifact
      uses: actions/upload-artifact@v2
      with:
        name: modelbox-release
        path: ${{github.workspace}}/build/release

  build_image:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: mkdir
        run: mkdir ./release
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: modelbox-release
          path: ./release/
      - name: Prepare
        run: |
          ls -lh ./release/*
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/Dockerfile.cuda102.develop
          build-args: |
            CUDA_VER=${{ env.CUDA_VER }}
            CUDA_VERSION=${{ env.CUDA_VERSION }}
            TORCH_VERSION=${{ env.TORCH_VERSION }}
            CUDA_CUDART_VERSION=${{ env.CUDA_CUDART_VERSION }}
            IMAGE_VERSION=${{ env.IMAGE_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_VERSION }}
